// Demo data generator for Smart Contacts.
//
// Provides a curated 50-contact bundle for first-run UX in EN and RU locales.
// Mirrors the authoring style of TaskOrchestrator's demo.ts — handcrafted, not procedural.
// Stable ULID factory per call so relationsInternal references resolve.
//
// Rules:
//  - Do NOT add procedural/random generation. All data is hand-authored.
//  - Do NOT use the module-level ulid() — use rndCrockford() to keep IDs stable within one call.
//  - relationsInternal must be mutual (mirror pairs) for consistency.
//  - Field-density targets (per locale, 50 contacts):
//      phones ≥1: 42–48, emails ≥1: 37–43, addresses ≥1: 15–21, events ≥1: 27–33,
//      organizations ≥1: 22–28, urls ≥1: 12–18, imClients ≥1: 7–13,
//      relationsExternal ≥1: 3–9, groups ≥1: 50/50, notesMd non-empty: 22–28,
//      userDefined non-empty: 2–6, tags ≥1: 50/50, relationsInternal ≥1: 17–23,
//      customFields non-empty: 9–15, lastContactedAt set: 32–38,
//      preferredChannel set: 27–33, priority set: 50/50,
//      socialDetected ≥1: 12–18, reminders ≥1: 7–13.

import type { Contact, CustomFieldDef, GroupMembership, Ulid } from '../types'
import type { DbAdapter } from '../db/adapter'
import { makeContactsRepo } from '../db/contactsRepo'
import { makeCustomFieldDefsRepo } from '../db/customFieldDefsRepo'
import { relIsoDate } from './date'

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface DemoBundle {
  contacts: Contact[]
  groups: GroupMembership[]
  customFieldDefs: CustomFieldDef[]
}

// ---------------------------------------------------------------------------
// ULID-like generator — Crockford Base32, fresh IDs every rndCrockford() call,
// but stable per slot number within one buildDemoContacts() invocation via idMap.
// ---------------------------------------------------------------------------

const ENC = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'

function rndCrockford(): Ulid {
  let s = ''
  for (let i = 0; i < 26; i++) s += ENC[(Math.random() * 32) | 0]!
  return s
}

// ---------------------------------------------------------------------------
// Build context
// ---------------------------------------------------------------------------

interface BuildCtx {
  locale: 'en' | 'ru'
  deviceId: string
  now: string
  idMap: Record<number, Ulid>
  defs: CustomFieldDef[]
  defIds: { coffee: Ulid; bonus: Ulid; metAt: Ulid }
}

function id(n: number, ctx: BuildCtx): Ulid {
  if (!ctx.idMap[n]) ctx.idMap[n] = rndCrockford()
  return ctx.idMap[n]!
}

function contact(slot: number, ctx: BuildCtx, lts: number, partial: Partial<Contact>): Contact {
  return {
    id: id(slot, ctx),
    createdAt: ctx.now,
    updatedAt: ctx.now,
    lamportTs: lts,
    deviceId: ctx.deviceId,
    ...partial,
  } as Contact
}

// ---------------------------------------------------------------------------
// English 50-contact array
// ---------------------------------------------------------------------------

function buildEn(ctx: BuildCtx): Contact[] {
  const c = (slot: number, lts: number, partial: Partial<Contact>) =>
    contact(slot, ctx, lts, partial)
  const { coffee, bonus, metAt } = ctx.defIds

  return [
    c(1, 1, {
      givenName: 'Alex',
      familyName: 'Carter',
      displayName: 'Alex Carter',
      phones: [{ value: '+1 555 0101', type: 'mobile', primary: true }],
      emails: [{ value: 'alex.carter@example.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Acme Corp', title: 'Senior Engineer', current: true, startDate: '2020-01-15' },
      ],
      events: [{ date: '1985-03-15', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['dev', 'mentor'],
      relationsInternal: [{ contactId: id(2, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-3) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Met at Acme onboarding 2020. Great mentor.',
      socialDetected: [{ platform: 'linkedin', handle: 'alex-carter' }],
    }),
    c(2, 2, {
      givenName: 'Maria',
      familyName: 'Garcia',
      displayName: 'Maria Garcia',
      phones: [{ value: '+1 555 0102', type: 'mobile', primary: true }],
      emails: [{ value: 'maria.garcia@example.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Acme Corp', title: 'Product Manager', current: true, startDate: '2019-06-01' },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['pm', 'agile'],
      relationsInternal: [{ contactId: id(1, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-1) + 'T14:30:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
    }),
    c(3, 3, {
      givenName: 'James',
      familyName: 'Wilson',
      displayName: 'James Wilson',
      phones: [{ value: '+1 555 0103', type: 'home', primary: true }],
      emails: [{ value: 'james.wilson@example.com', type: 'personal', primary: true }],
      events: [
        { date: '1978-11-08', type: 'birthday' },
        { date: '2005-06-12', type: 'anniversary' },
      ],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['old-friend', 'hiking'],
      relationsInternal: [{ contactId: id(4, ctx), type: 'spouse' }],
      lastContactedAt: relIsoDate(-14) + 'T18:00:00.000Z',
      preferredChannel: 'phone',
      priority: 3,
      notesMd: 'Knows since college. Loves hiking and craft beer.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(7) + 'T09:00:00.000Z',
          text: 'Call James for birthday',
          done: false,
        },
      ],
    }),
    c(4, 4, {
      givenName: 'Emily',
      familyName: 'Brown',
      displayName: 'Emily Brown',
      phones: [{ value: '+1 555 0104', type: 'mobile', primary: true }],
      emails: [{ value: 'emily.brown@example.com', type: 'personal', primary: true }],
      addresses: [
        {
          street: '42 Oak Street',
          city: 'Boston',
          region: 'MA',
          postal: '02101',
          country: 'US',
          type: 'home',
          primary: true,
        },
      ],
      events: [{ date: '1980-02-14', type: 'birthday' }],
      groups: [
        { id: 'g_friends', name: 'Friends' },
        { id: 'g_family', name: 'Family' },
      ],
      tags: ['family', 'close'],
      relationsInternal: [{ contactId: id(3, ctx), type: 'spouse' }],
      lastContactedAt: relIsoDate(-2) + 'T11:00:00.000Z',
      preferredChannel: 'email',
      priority: 1,
    }),
    c(5, 5, {
      givenName: 'David',
      familyName: 'Lee',
      displayName: 'David Lee',
      phones: [
        { value: '+1 555 0105', type: 'mobile', primary: true },
        { value: '+1 555 0205', type: 'work' },
      ],
      emails: [{ value: 'david.lee@techcorp.io', type: 'work', primary: true }],
      organizations: [{ name: 'TechCorp', title: 'CTO', current: true, startDate: '2018-03-01' }],
      urls: [{ value: 'https://davidlee.dev', type: 'blog' }],
      events: [{ date: '1982-09-30', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Work' },
        { id: 'g_clients', name: 'Clients' },
      ],
      tags: ['vip', 'tech', 'investor'],
      relationsInternal: [{ contactId: id(6, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-5) + 'T09:30:00.000Z',
      preferredChannel: 'email',
      priority: 1,
      notesMd: 'Key decision maker at TechCorp. Prefers Slack DMs.',
      socialDetected: [{ platform: 'twitter', handle: '@davidlee_tech' }],
      customFields: { [coffee]: 'Espresso' },
    }),
    c(6, 6, {
      givenName: 'Sophie',
      familyName: 'Anderson',
      displayName: 'Sophie Anderson',
      phones: [{ value: '+1 555 0106', type: 'mobile', primary: true }],
      emails: [{ value: 'sophie@anderson.me', type: 'personal', primary: true }],
      addresses: [
        {
          street: '7 Pine Ave',
          city: 'Chicago',
          region: 'IL',
          postal: '60601',
          country: 'US',
          type: 'home',
        },
      ],
      events: [{ date: '1992-05-18', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['yoga', 'art'],
      relationsInternal: [{ contactId: id(5, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-10) + 'T20:00:00.000Z',
      priority: 3,
    }),
    c(7, 7, {
      givenName: 'Michael',
      familyName: 'Chen',
      displayName: 'Michael Chen',
      phones: [{ value: '+1 555 0107', type: 'mobile', primary: true }],
      emails: [{ value: 'mchen@lawfirm.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Chen & Associates', title: 'Partner', current: true, startDate: '2015-07-01' },
      ],
      urls: [{ value: 'https://chenlaw.com', type: 'work' }],
      events: [{ date: '1975-12-25', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['legal', 'vip'],
      relationsInternal: [{ contactId: id(8, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-7) + 'T15:00:00.000Z',
      preferredChannel: 'email',
      priority: 1,
      notesMd: 'Corporate attorney. Handles IP and contracts.',
      customFields: { [bonus]: 'CL-9981234' },
    }),
    c(8, 8, {
      givenName: 'Olivia',
      familyName: 'Martinez',
      displayName: 'Olivia Martinez',
      phones: [{ value: '+1 555 0108', type: 'mobile', primary: true }],
      organizations: [
        { name: 'Chen & Associates', title: 'Associate', current: true, startDate: '2021-01-15' },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['legal', 'junior'],
      relationsInternal: [{ contactId: id(7, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-4) + 'T11:30:00.000Z',
      priority: 3,
    }),
    c(9, 9, {
      givenName: 'Daniel',
      familyName: 'Taylor',
      displayName: 'Daniel Taylor',
      phones: [{ value: '+1 555 0109', type: 'mobile', primary: true }],
      emails: [{ value: 'dtaylor@medclinic.com', type: 'work', primary: true }],
      organizations: [
        { name: 'City Medical Clinic', title: 'Physician', current: true, startDate: '2012-09-01' },
      ],
      addresses: [
        {
          street: '100 Medical Dr',
          city: 'New York',
          region: 'NY',
          postal: '10001',
          country: 'US',
          type: 'work',
        },
      ],
      events: [{ date: '1977-04-11', type: 'birthday' }],
      groups: [{ id: 'g_doctors', name: 'Doctors' }],
      tags: ['doctor', 'health'],
      relationsInternal: [{ contactId: id(10, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-30) + 'T09:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Primary care doctor. Annual checkup in June.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(60) + 'T09:00:00.000Z',
          text: 'Annual checkup',
          done: false,
        },
      ],
    }),
    c(10, 10, {
      givenName: 'Emma',
      familyName: 'Davis',
      displayName: 'Emma Davis',
      phones: [{ value: '+1 555 0110', type: 'mobile', primary: true }],
      emails: [{ value: 'emma.davis@medclinic.com', type: 'work', primary: true }],
      groups: [{ id: 'g_health', name: 'Health' }],
      tags: ['health', 'nurse'],
      relationsInternal: [{ contactId: id(9, ctx), type: 'colleague' }],
      priority: 3,
    }),
    c(11, 11, {
      givenName: 'Noah',
      familyName: 'Miller',
      displayName: 'Noah Miller',
      phones: [{ value: '+1 555 0111', type: 'mobile', primary: true }],
      emails: [{ value: 'noah@miller-realty.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Miller Realty', title: 'Agent', current: true, startDate: '2017-05-01' },
      ],
      urls: [{ value: 'https://miller-realty.com', type: 'work' }],
      events: [{ date: '1988-06-30', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['realty', 'housing'],
      lastContactedAt: relIsoDate(-20) + 'T16:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Helped find current apartment. Knows good neighborhoods.',
    }),
    c(12, 12, {
      givenName: 'Ava',
      familyName: 'Johnson',
      displayName: 'Ava Johnson',
      phones: [{ value: '+1 555 0112', type: 'mobile', primary: true }],
      emails: [{ value: 'ava.j@university.edu', type: 'work', primary: true }],
      organizations: [
        { name: 'State University', title: 'Professor', current: true, startDate: '2014-08-01' },
      ],
      addresses: [{ city: 'Cambridge', region: 'MA', country: 'US', type: 'work' }],
      events: [{ date: '1979-10-05', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'School' }],
      tags: ['academia', 'mentor'],
      lastContactedAt: relIsoDate(-45) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      imClients: [{ protocol: 'skype', handle: 'ava.johnson.edu' }],
    }),
    c(13, 13, {
      givenName: 'Liam',
      familyName: 'Robinson',
      displayName: 'Liam Robinson',
      phones: [{ value: '+1 555 0113', type: 'mobile', primary: true }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'nephew'],
      relationsExternal: [{ person: 'John Robinson', type: 'father' }],
      priority: 2,
      notesMd: 'Nephew. Starting college this fall.',
    }),
    c(14, 14, {
      givenName: 'Mia',
      familyName: 'Hall',
      displayName: 'Mia Hall',
      phones: [{ value: '+1 555 0114', type: 'mobile', primary: true }],
      emails: [{ value: 'mia.hall@designco.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Design Co', title: 'UX Designer', current: true, startDate: '2022-02-01' },
      ],
      urls: [{ value: 'https://miahall.design', type: 'portfolio' }],
      events: [{ date: '1993-09-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['design', 'ux', 'creative'],
      relationsInternal: [{ contactId: id(15, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-6) + 'T13:00:00.000Z',
      preferredChannel: 'slack',
      priority: 2,
      socialDetected: [{ platform: 'behance', handle: 'mia-hall' }],
      customFields: { [coffee]: 'Latte' },
    }),
    c(15, 15, {
      givenName: 'Lucas',
      familyName: 'White',
      displayName: 'Lucas White',
      phones: [{ value: '+1 555 0115', type: 'mobile', primary: true }],
      emails: [{ value: 'lwhite@designco.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Design Co', title: 'Art Director', current: true, startDate: '2020-09-01' },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['design', 'branding'],
      relationsInternal: [{ contactId: id(14, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-8) + 'T15:30:00.000Z',
      priority: 3,
    }),
    c(16, 16, {
      givenName: 'Isabella',
      familyName: 'King',
      displayName: 'Isabella King',
      phones: [{ value: '+1 555 0116', type: 'mobile', primary: true }],
      emails: [{ value: 'bella.king@fitness.com', type: 'work', primary: true }],
      organizations: [
        { name: 'FitLife Gym', title: 'Personal Trainer', current: true, startDate: '2018-01-01' },
      ],
      events: [{ date: '1990-12-03', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Health' }],
      tags: ['fitness', 'coach', 'health'],
      lastContactedAt: relIsoDate(-7) + 'T07:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Personal trainer. Sessions Mon/Wed/Fri 7am.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(1) + 'T06:30:00.000Z',
          text: 'Morning session',
          done: false,
        },
      ],
    }),
    c(17, 17, {
      givenName: 'Henry',
      familyName: 'Scott',
      displayName: 'Henry Scott',
      addresses: [
        {
          street: '88 Elm Road',
          city: 'Seattle',
          region: 'WA',
          postal: '98101',
          country: 'US',
          type: 'home',
        },
      ],
      events: [{ date: '1983-05-07', type: 'birthday' }],
      groups: [
        { id: 'g_friends', name: 'Friends' },
        { id: 'g_school', name: 'School' },
      ],
      tags: ['college', 'friend', 'gamer'],
      lastContactedAt: relIsoDate(-21) + 'T19:00:00.000Z',
      priority: 3,
    }),
    c(18, 18, {
      givenName: 'Charlotte',
      familyName: 'Adams',
      displayName: 'Charlotte Adams',
      phones: [{ value: '+1 555 0118', type: 'mobile', primary: true }],
      emails: [{ value: 'charlotte@bigbank.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Big Bank', title: 'Financial Advisor', current: true, startDate: '2016-04-01' },
      ],
      events: [{ date: '1984-08-28', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['finance', 'advisor'],
      relationsInternal: [{ contactId: id(19, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-15) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Manages investment portfolio. Annual review in March.',
      customFields: { [metAt]: '2019-03-15' },
    }),
    c(19, 19, {
      givenName: 'Ethan',
      familyName: 'Wright',
      displayName: 'Ethan Wright',
      phones: [{ value: '+1 555 0119', type: 'mobile', primary: true }],
      emails: [{ value: 'ewright@bigbank.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Big Bank', title: 'Senior Analyst', current: true, startDate: '2020-07-01' },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['finance', 'analyst'],
      relationsInternal: [{ contactId: id(18, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-9) + 'T14:00:00.000Z',
      priority: 3,
    }),
    c(20, 20, {
      givenName: 'Amelia',
      familyName: 'Green',
      displayName: 'Amelia Green',
      phones: [{ value: '+1 555 0120', type: 'mobile', primary: true }],
      emails: [{ value: 'amelia.green@example.com', type: 'personal', primary: true }],
      events: [{ date: '1989-04-01', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'sister'],
      relationsExternal: [{ person: 'Robert Green', type: 'father' }],
      lastContactedAt: relIsoDate(-3) + 'T20:00:00.000Z',
      preferredChannel: 'phone',
      priority: 1,
      notesMd: 'Sister. Lives in Portland. Call every Sunday.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(6) + 'T19:00:00.000Z',
          text: 'Sunday call',
          done: false,
        },
      ],
    }),
    c(21, 21, {
      givenName: 'William',
      familyName: 'Baker',
      displayName: 'William Baker',
      phones: [{ value: '+1 555 0121', type: 'mobile', primary: true }],
      emails: [{ value: 'wbaker@startup.io', type: 'work', primary: true }],
      organizations: [
        { name: 'BakerTech', title: 'Founder', current: true, startDate: '2021-01-01' },
      ],
      urls: [
        { value: 'https://bakertech.io', type: 'work' },
        { value: 'https://linkedin.com/in/wbaker', type: 'linkedin' },
      ],
      events: [{ date: '1986-02-20', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Work' },
        { id: 'g_clients', name: 'Clients' },
      ],
      tags: ['startup', 'founder', 'investor'],
      relationsInternal: [{ contactId: id(22, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-11) + 'T16:00:00.000Z',
      preferredChannel: 'email',
      priority: 1,
      notesMd: 'Startup founder in the SaaS space. Good networking contact.',
      socialDetected: [
        { platform: 'linkedin', handle: 'wbaker' },
        { platform: 'twitter', handle: '@wbaker_builds' },
      ],
    }),
    c(22, 22, {
      givenName: 'Harper',
      familyName: 'Nelson',
      displayName: 'Harper Nelson',
      phones: [{ value: '+1 555 0122', type: 'mobile', primary: true }],
      emails: [{ value: 'hnelson@startup.io', type: 'work', primary: true }],
      organizations: [{ name: 'BakerTech', title: 'COO', current: true, startDate: '2021-03-01' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['startup', 'ops'],
      relationsInternal: [{ contactId: id(21, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-12) + 'T11:00:00.000Z',
      preferredChannel: 'slack',
      priority: 2,
    }),
    c(23, 23, {
      givenName: 'Benjamin',
      familyName: 'Hill',
      displayName: 'Benjamin Hill',
      phones: [{ value: '+1 555 0123', type: 'mobile', primary: true }],
      emails: [{ value: 'ben.hill@example.com', type: 'personal', primary: true }],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['poker', 'fantasy-sports'],
      imClients: [{ protocol: 'discord', handle: 'benhill#4521' }],
      lastContactedAt: relIsoDate(-18) + 'T21:00:00.000Z',
      priority: 3,
    }),
    c(24, 24, {
      givenName: 'Evelyn',
      familyName: 'Cook',
      displayName: 'Evelyn Cook',
      phones: [{ value: '+1 555 0124', type: 'mobile', primary: true }],
      emails: [{ value: 'ecook@schooldistrict.edu', type: 'work', primary: true }],
      groups: [{ id: 'g_school', name: 'School' }],
      tags: ['teacher', 'education'],
      priority: 3,
      notesMd: "Children's school teacher.",
    }),
    c(25, 25, {
      givenName: 'Jacob',
      familyName: 'Rivera',
      displayName: 'Jacob Rivera',
      emails: [{ value: 'jacob.r@example.com', type: 'personal', primary: true }],
      addresses: [
        {
          street: '15 Sunset Blvd',
          city: 'Los Angeles',
          region: 'CA',
          postal: '90001',
          country: 'US',
          type: 'home',
        },
      ],
      events: [{ date: '1986-12-17', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['music', 'guitar', 'jamming'],
      imClients: [{ protocol: 'telegram', handle: '@jacob_rivera' }],
      lastContactedAt: relIsoDate(-28) + 'T22:00:00.000Z',
      priority: 3,
    }),
    c(26, 26, {
      givenName: 'Abigail',
      familyName: 'Carter',
      displayName: 'Abigail Carter',
      phones: [{ value: '+1 555 0126', type: 'mobile', primary: true }],
      emails: [{ value: 'abigail.carter@example.com', type: 'personal', primary: true }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'cousin'],
      relationsExternal: [{ person: 'Tom Carter', type: 'father' }],
      priority: 2,
    }),
    c(27, 27, {
      givenName: 'Samuel',
      familyName: 'Cooper',
      displayName: 'Samuel Cooper',
      phones: [{ value: '+1 555 0127', type: 'mobile', primary: true }],
      emails: [{ value: 'scooper@writersblock.com', type: 'work', primary: true }],
      urls: [{ value: 'https://samuelcooper.writing.com', type: 'blog' }],
      events: [{ date: '1979-06-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['writing', 'editor', 'books'],
      lastContactedAt: relIsoDate(-22) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 3,
      notesMd: 'Freelance editor. Good for content review.',
    }),
    c(28, 28, {
      givenName: 'Sofia',
      familyName: 'Reed',
      displayName: 'Sofia Reed',
      phones: [{ value: '+1 555 0128', type: 'mobile', primary: true }],
      events: [{ date: '1994-02-28', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Health' }],
      tags: ['yoga', 'meditation', 'wellness'],
      imClients: [{ protocol: 'whatsapp', handle: '+1 555 0128' }],
      lastContactedAt: relIsoDate(-13) + 'T08:00:00.000Z',
      priority: 3,
    }),
    c(29, 29, {
      givenName: 'Logan',
      familyName: 'Bell',
      displayName: 'Logan Bell',
      phones: [{ value: '+1 555 0129', type: 'mobile', primary: true }],
      emails: [{ value: 'logan.bell@infosec.io', type: 'work', primary: true }],
      organizations: [
        {
          name: 'InfoSec Solutions',
          title: 'Security Engineer',
          current: true,
          startDate: '2021-06-01',
        },
      ],
      urls: [{ value: 'https://github.com/loganbell', type: 'github' }],
      events: [{ date: '1990-04-22', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['security', 'dev', 'ctf'],
      relationsInternal: [{ contactId: id(30, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-16) + 'T17:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      socialDetected: [{ platform: 'github', handle: 'loganbell' }],
    }),
    c(30, 30, {
      givenName: 'Ella',
      familyName: 'Murphy',
      displayName: 'Ella Murphy',
      phones: [{ value: '+1 555 0130', type: 'mobile', primary: true }],
      emails: [{ value: 'ella.murphy@infosec.io', type: 'work', primary: true }],
      organizations: [
        {
          name: 'InfoSec Solutions',
          title: 'DevOps Engineer',
          current: true,
          startDate: '2022-01-15',
        },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['devops', 'cloud'],
      relationsInternal: [{ contactId: id(29, ctx), type: 'colleague' }],
      priority: 3,
    }),
    c(31, 31, {
      givenName: 'Jack',
      familyName: 'Bailey',
      displayName: 'Jack Bailey',
      phones: [{ value: '+1 555 0131', type: 'mobile', primary: true }],
      addresses: [{ city: 'Orlando', region: 'FL', country: 'US', type: 'home' }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'uncle'],
      priority: 2,
      notesMd: 'Uncle Jack. Retired, lives in Florida.',
    }),
    c(32, 32, {
      givenName: 'Aria',
      familyName: 'Cox',
      displayName: 'Aria Cox',
      phones: [{ value: '+1 555 0132', type: 'mobile', primary: true }],
      emails: [{ value: 'aria.cox@pr-agency.com', type: 'work', primary: true }],
      organizations: [
        { name: 'PR Partners', title: 'PR Manager', current: true, startDate: '2018-08-01' },
      ],
      events: [{ date: '1988-11-20', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Work' },
        { id: 'g_clients', name: 'Clients' },
      ],
      tags: ['pr', 'media', 'networking'],
      lastContactedAt: relIsoDate(-8) + 'T12:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Key contact for press releases. Knows every journalist in town.',
      socialDetected: [{ platform: 'twitter', handle: '@aria_cox_pr' }],
    }),
    c(33, 33, {
      givenName: 'Owen',
      familyName: 'Howard',
      displayName: 'Owen Howard',
      phones: [{ value: '+1 555 0133', type: 'mobile', primary: true }],
      emails: [{ value: 'owen@howardplumbing.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Howard Plumbing', title: 'Owner', current: true, startDate: '2010-01-01' },
      ],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['plumber', 'home-services'],
      priority: 3,
    }),
    c(34, 34, {
      givenName: 'Layla',
      familyName: 'Ward',
      displayName: 'Layla Ward',
      phones: [{ value: '+1 555 0134', type: 'mobile', primary: true }],
      emails: [{ value: 'lward@greenfinance.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Green Finance Ltd', title: 'Accountant', current: true, startDate: '2020-04-01' },
      ],
      addresses: [{ city: 'San Francisco', region: 'CA', country: 'US', type: 'work' }],
      events: [{ date: '1990-03-27', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['accounting', 'tax'],
      lastContactedAt: relIsoDate(-40) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'CPA. Handles annual taxes.',
      customFields: { [metAt]: '2020-02-10' },
    }),
    c(35, 35, {
      givenName: 'Aiden',
      familyName: 'Foster',
      displayName: 'Aiden Foster',
      phones: [{ value: '+1 555 0135', type: 'mobile', primary: true }],
      events: [{ date: '1996-05-01', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'School' }],
      tags: ['classmate', 'study-group'],
      imClients: [{ protocol: 'discord', handle: 'aiden#7823' }],
      priority: 3,
    }),
    c(36, 36, {
      givenName: 'Zoe',
      familyName: 'Russell',
      displayName: 'Zoe Russell',
      phones: [{ value: '+1 555 0136', type: 'mobile', primary: true }],
      emails: [{ value: 'zoe@nutritionplus.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Nutrition Plus', title: 'Dietitian', current: true, startDate: '2019-01-01' },
      ],
      events: [{ date: '1987-08-17', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Health' }],
      tags: ['nutrition', 'health', 'wellness'],
      lastContactedAt: relIsoDate(-25) + 'T12:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Nutritionist. Follow up on diet plan every 3 months.',
      customFields: { [coffee]: 'Black' },
    }),
    c(37, 37, {
      givenName: 'Elijah',
      familyName: 'Sanders',
      displayName: 'Elijah Sanders',
      phones: [{ value: '+1 555 0137', type: 'mobile', primary: true }],
      emails: [{ value: 'esanders@techsupport.com', type: 'work', primary: true }],
      addresses: [{ city: 'Phoenix', region: 'AZ', country: 'US', type: 'home' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['support', 'it'],
      lastContactedAt: relIsoDate(-5) + 'T09:00:00.000Z',
      priority: 3,
    }),
    c(38, 38, {
      givenName: 'Lily',
      familyName: 'Price',
      displayName: 'Lily Price',
      phones: [{ value: '+1 555 0138', type: 'mobile', primary: true }],
      emails: [{ value: 'lily.price@example.com', type: 'personal', primary: true }],
      addresses: [
        {
          street: '200 Maple Lane',
          city: 'Austin',
          region: 'TX',
          postal: '73301',
          country: 'US',
          type: 'home',
        },
      ],
      events: [{ date: '1992-06-06', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['travel', 'photography'],
      imClients: [{ protocol: 'instagram', handle: '@lily.price.photos' }],
      lastContactedAt: relIsoDate(-17) + 'T18:00:00.000Z',
      preferredChannel: 'instagram',
      priority: 3,
      socialDetected: [{ platform: 'instagram', handle: 'lily.price.photos' }],
    }),
    c(39, 39, {
      givenName: 'Mason',
      familyName: 'Bennett',
      displayName: 'Mason Bennett',
      phones: [{ value: '+1 555 0139', type: 'mobile', primary: true }],
      emails: [{ value: 'mbennett@growthco.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Growth Co', title: 'Marketing Director', current: true, startDate: '2019-05-01' },
      ],
      urls: [{ value: 'https://growthco.com', type: 'work' }],
      events: [{ date: '1985-10-13', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['marketing', 'growth', 'seo'],
      relationsInternal: [{ contactId: id(40, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-6) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Marketing partner. Works on joint campaigns.',
      socialDetected: [{ platform: 'linkedin', handle: 'mason-bennett' }],
    }),
    c(40, 40, {
      givenName: 'Riley',
      familyName: 'Brooks',
      displayName: 'Riley Brooks',
      phones: [{ value: '+1 555 0140', type: 'mobile', primary: true }],
      emails: [{ value: 'riley.brooks@growthco.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Growth Co', title: 'Content Strategist', current: true, startDate: '2020-09-01' },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['content', 'copywriting'],
      relationsInternal: [{ contactId: id(39, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-13) + 'T16:00:00.000Z',
      priority: 3,
    }),
    c(41, 41, {
      givenName: 'Carter',
      familyName: 'Ross',
      displayName: 'Carter Ross',
      phones: [{ value: '+1 555 0141', type: 'mobile', primary: true }],
      emails: [{ value: 'carter.ross@example.com', type: 'personal', primary: true }],
      addresses: [{ city: 'Nashville', region: 'TN', country: 'US', type: 'home' }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'brother-in-law'],
      relationsExternal: [{ person: 'Emily Brown', type: 'sister' }],
      priority: 2,
    }),
    c(42, 42, {
      givenName: 'Nora',
      familyName: 'Long',
      displayName: 'Nora Long',
      phones: [{ value: '+1 555 0142', type: 'mobile', primary: true }],
      emails: [{ value: 'nlong@cityarchitects.com', type: 'work', primary: true }],
      organizations: [
        { name: 'City Architects', title: 'Architect', current: true, startDate: '2017-03-01' },
      ],
      urls: [{ value: 'https://cityarchitects.com/nora', type: 'portfolio' }],
      events: [{ date: '1986-04-04', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['architecture', 'design'],
      lastContactedAt: relIsoDate(-22) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 3,
      notesMd: 'Working on home renovation project planning.',
    }),
    c(43, 43, {
      givenName: 'Theodore',
      familyName: 'Powell',
      displayName: 'Theodore Powell',
      phones: [{ value: '+1 555 0143', type: 'mobile', primary: true }],
      addresses: [{ city: 'Phoenix', region: 'AZ', country: 'US', type: 'home' }],
      groups: [{ id: 'g_family', name: 'Family' }],
      tags: ['family', 'grandfather'],
      priority: 1,
      notesMd: 'Grandfather. Calls every Sunday.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(0) + 'T18:00:00.000Z',
          text: 'Sunday call with grandpa',
          done: false,
        },
      ],
    }),
    c(44, 44, {
      givenName: 'Aurora',
      familyName: 'Sullivan',
      displayName: 'Aurora Sullivan',
      phones: [{ value: '+1 555 0144', type: 'mobile', primary: true }],
      emails: [{ value: 'aurora@wellnessretreat.com', type: 'work', primary: true }],
      events: [{ date: '1991-03-21', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Health' }],
      tags: ['yoga', 'mindfulness', 'wellness'],
      imClients: [{ protocol: 'telegram', handle: '@aurora_yoga' }],
      lastContactedAt: relIsoDate(-7) + 'T08:30:00.000Z',
      preferredChannel: 'telegram',
      priority: 3,
    }),
    c(45, 45, {
      givenName: 'Asher',
      familyName: 'Watson',
      displayName: 'Asher Watson',
      phones: [{ value: '+1 555 0145', type: 'mobile', primary: true }],
      emails: [{ value: 'asher.watson@cloudsystems.com', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Cloud Systems LLC',
          title: 'Solutions Architect',
          current: true,
          startDate: '2018-11-01',
        },
      ],
      addresses: [{ city: 'Denver', region: 'CO', country: 'US', type: 'home' }],
      events: [{ date: '1987-11-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['cloud', 'aws', 'architecture'],
      relationsInternal: [{ contactId: id(46, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-4) + 'T13:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Cloud migration specialist. AWS certified.',
      socialDetected: [{ platform: 'linkedin', handle: 'asher-watson-cloud' }],
      customFields: { [coffee]: 'Americano', [metAt]: '2022-05-12' },
    }),
    c(46, 46, {
      givenName: 'Hazel',
      familyName: 'Hughes',
      displayName: 'Hazel Hughes',
      phones: [{ value: '+1 555 0146', type: 'mobile', primary: true }],
      emails: [{ value: 'hhughes@cloudsystems.com', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Cloud Systems LLC',
          title: 'Project Manager',
          current: true,
          startDate: '2019-02-01',
        },
      ],
      groups: [{ id: 'g_work', name: 'Work' }],
      tags: ['pm', 'agile', 'cloud'],
      relationsInternal: [{ contactId: id(45, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-9) + 'T15:00:00.000Z',
      priority: 3,
    }),
    c(47, 47, {
      givenName: 'Levi',
      familyName: 'Coleman',
      displayName: 'Levi Coleman',
      phones: [{ value: '+1 555 0147', type: 'mobile', primary: true }],
      emails: [{ value: 'levi@colemanlaw.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Coleman Law Group', title: 'Attorney', current: true, startDate: '2016-01-01' },
      ],
      groups: [{ id: 'g_clients', name: 'Clients' }],
      tags: ['legal', 'attorney'],
      preferredChannel: 'email',
      priority: 2,
    }),
    c(48, 48, {
      givenName: 'Eleanor',
      familyName: 'Jenkins',
      displayName: 'Eleanor Jenkins',
      phones: [{ value: '+1 555 0148', type: 'mobile', primary: true }],
      emails: [{ value: 'ejenkins@schooldistrict.edu', type: 'work', primary: true }],
      groups: [{ id: 'g_school', name: 'School' }],
      tags: ['education', 'principal'],
      priority: 3,
      notesMd: "School principal. Contact for kids' school events.",
    }),
    c(49, 49, {
      givenName: 'Sebastian',
      familyName: 'Perry',
      displayName: 'Sebastian Perry',
      phones: [{ value: '+1 555 0149', type: 'mobile', primary: true }],
      emails: [{ value: 'sperry@dentist-care.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Bright Smile Dental', title: 'Dentist', current: true, startDate: '2014-05-01' },
      ],
      addresses: [
        {
          street: '500 Dental Way',
          city: 'Boston',
          region: 'MA',
          postal: '02110',
          country: 'US',
          type: 'work',
        },
      ],
      events: [{ date: '1978-08-22', type: 'birthday' }],
      groups: [{ id: 'g_doctors', name: 'Doctors' }],
      tags: ['dentist', 'health'],
      lastContactedAt: relIsoDate(-180) + 'T11:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Dentist. 6-month checkup due.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(30) + 'T10:00:00.000Z',
          text: 'Schedule dental checkup',
          done: false,
        },
      ],
      userDefined: { appointmentFrequency: 'biannual' },
    }),
    c(50, 50, {
      givenName: 'Stella',
      familyName: 'Foster',
      displayName: 'Stella Foster',
      phones: [{ value: '+1 555 0150', type: 'mobile', primary: true }],
      emails: [{ value: 'stella.foster@example.com', type: 'personal', primary: true }],
      addresses: [
        {
          street: '3 Harbor View',
          city: 'Miami',
          region: 'FL',
          postal: '33101',
          country: 'US',
          type: 'home',
        },
      ],
      events: [{ date: '1995-04-10', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Friends' }],
      tags: ['travel', 'beach', 'sailing'],
      imClients: [{ protocol: 'whatsapp', handle: '+1 555 0150' }],
      lastContactedAt: relIsoDate(-24) + 'T19:00:00.000Z',
      preferredChannel: 'whatsapp',
      priority: 3,
      notesMd: 'Old college friend. Lives in Miami. Met during spring break 2016.',
      socialDetected: [{ platform: 'instagram', handle: 'stella.foster.miami' }],
      customFields: { [bonus]: 'SF-5521987' },
      userDefined: { vacationCity: 'Miami' },
    }),
  ]
}

// ---------------------------------------------------------------------------
// Russian 50-contact array
// ---------------------------------------------------------------------------

function buildRu(ctx: BuildCtx): Contact[] {
  const c = (slot: number, lts: number, partial: Partial<Contact>) =>
    contact(slot, ctx, lts, partial)
  const { coffee, bonus, metAt } = ctx.defIds

  return [
    c(1, 1, {
      givenName: 'Иван',
      familyName: 'Иванов',
      displayName: 'Иван Иванов',
      phones: [{ value: '+7 916 001 0001', type: 'mobile', primary: true }],
      emails: [{ value: 'ivan.ivanov@company.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'ООО Технологии',
          title: 'Старший разработчик',
          current: true,
          startDate: '2020-03-01',
        },
      ],
      events: [{ date: '1985-06-12', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['dev', 'backend'],
      relationsInternal: [{ contactId: id(2, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-2) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Познакомились на митапе по Go. Отличный специалист.',
      socialDetected: [{ platform: 'habr', handle: 'ivan_ivanov' }],
    }),
    c(2, 2, {
      givenName: 'Мария',
      familyName: 'Петрова',
      displayName: 'Мария Петрова',
      phones: [{ value: '+7 916 001 0002', type: 'mobile', primary: true }],
      emails: [{ value: 'mpetrov@company.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'ООО Технологии',
          title: 'Продакт-менеджер',
          current: true,
          startDate: '2019-09-01',
        },
      ],
      events: [{ date: '1990-08-25', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['pm', 'agile'],
      relationsInternal: [{ contactId: id(1, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-1) + 'T15:00:00.000Z',
      preferredChannel: 'telegram',
      priority: 2,
    }),
    c(3, 3, {
      givenName: 'Александр',
      familyName: 'Смирнов',
      displayName: 'Александр Смирнов',
      phones: [{ value: '+7 916 001 0003', type: 'mobile', primary: true }],
      emails: [{ value: 'alex.smirnov@example.ru', type: 'personal', primary: true }],
      events: [
        { date: '1978-10-15', type: 'birthday' },
        { date: '2007-09-01', type: 'anniversary' },
      ],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['старый друг', 'рыбалка'],
      relationsInternal: [{ contactId: id(4, ctx), type: 'spouse' }],
      lastContactedAt: relIsoDate(-14) + 'T19:00:00.000Z',
      preferredChannel: 'phone',
      priority: 3,
      notesMd: 'Знакомы со школы. Любит рыбалку и баню.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(10) + 'T09:00:00.000Z',
          text: 'Поздравить с годовщиной',
          done: false,
        },
      ],
    }),
    c(4, 4, {
      givenName: 'Анна',
      familyName: 'Кузнецова',
      displayName: 'Анна Кузнецова',
      phones: [{ value: '+7 916 001 0004', type: 'mobile', primary: true }],
      emails: [{ value: 'anna.kuznecova@example.ru', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'ул. Ленина 42',
          city: 'Москва',
          region: 'Московская обл',
          postal: '101000',
          country: 'RU',
          type: 'home',
          primary: true,
        },
      ],
      events: [{ date: '1980-03-08', type: 'birthday' }],
      groups: [
        { id: 'g_friends', name: 'Друзья' },
        { id: 'g_family', name: 'Семья' },
      ],
      tags: ['семья', 'близкий'],
      relationsInternal: [{ contactId: id(3, ctx), type: 'spouse' }],
      lastContactedAt: relIsoDate(-3) + 'T12:00:00.000Z',
      preferredChannel: 'phone',
      priority: 1,
    }),
    c(5, 5, {
      givenName: 'Дмитрий',
      familyName: 'Попов',
      displayName: 'Дмитрий Попов',
      phones: [
        { value: '+7 916 001 0005', type: 'mobile', primary: true },
        { value: '+7 495 001 0005', type: 'work' },
      ],
      emails: [{ value: 'dpopov@bigtech.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'BigTech ОАО',
          title: 'Технический директор',
          current: true,
          startDate: '2018-01-01',
        },
      ],
      urls: [{ value: 'https://dpopov.tech', type: 'blog' }],
      events: [{ date: '1982-11-23', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Работа' },
        { id: 'g_clients', name: 'Клиенты' },
      ],
      tags: ['vip', 'технология', 'инвестор'],
      relationsInternal: [{ contactId: id(6, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-5) + 'T09:30:00.000Z',
      preferredChannel: 'email',
      priority: 1,
      notesMd: 'Технический директор BigTech. Предпочитает переписку по email.',
      socialDetected: [{ platform: 'linkedin', handle: 'dmitry-popov-cto' }],
      customFields: { [coffee]: 'Эспрессо' },
    }),
    c(6, 6, {
      givenName: 'Елена',
      familyName: 'Соколова',
      displayName: 'Елена Соколова',
      phones: [{ value: '+7 916 001 0006', type: 'mobile', primary: true }],
      emails: [{ value: 'elena@sokolova.me', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'Проспект Мира 7',
          city: 'Санкт-Петербург',
          region: 'Ленинградская обл',
          postal: '190000',
          country: 'RU',
          type: 'home',
        },
      ],
      events: [{ date: '1992-04-16', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['арт', 'живопись'],
      relationsInternal: [{ contactId: id(5, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-10) + 'T20:00:00.000Z',
      priority: 3,
    }),
    c(7, 7, {
      givenName: 'Сергей',
      familyName: 'Лебедев',
      displayName: 'Сергей Лебедев',
      phones: [{ value: '+7 916 001 0007', type: 'mobile', primary: true }],
      emails: [{ value: 'serg@leblaw.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Адвокатское бюро «Лебедев»',
          title: 'Партнёр',
          current: true,
          startDate: '2015-07-01',
        },
      ],
      urls: [{ value: 'https://leblaw.ru', type: 'work' }],
      events: [{ date: '1975-12-30', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['юрист', 'vip'],
      relationsInternal: [{ contactId: id(8, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-7) + 'T15:00:00.000Z',
      preferredChannel: 'email',
      priority: 1,
      notesMd: 'Корпоративный адвокат. Занимается IP и договорами.',
      customFields: { [bonus]: 'ЛЮ-998123' },
    }),
    c(8, 8, {
      givenName: 'Татьяна',
      familyName: 'Козлова',
      displayName: 'Татьяна Козлова',
      phones: [{ value: '+7 916 001 0008', type: 'mobile', primary: true }],
      emails: [{ value: 'tkozlov@leblaw.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Адвокатское бюро «Лебедев»',
          title: 'Ассоциат',
          current: true,
          startDate: '2021-01-15',
        },
      ],
      events: [{ date: '1994-07-19', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['юрист', 'молодой специалист'],
      relationsInternal: [{ contactId: id(7, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-4) + 'T11:30:00.000Z',
      priority: 3,
    }),
    c(9, 9, {
      givenName: 'Андрей',
      familyName: 'Новиков',
      displayName: 'Андрей Новиков',
      phones: [{ value: '+7 916 001 0009', type: 'mobile', primary: true }],
      emails: [{ value: 'anovikov@medcenter.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Медцентр «Здоровье»', title: 'Терапевт', current: true, startDate: '2012-09-01' },
      ],
      addresses: [
        {
          street: 'ул. Садовая 100',
          city: 'Москва',
          region: 'Московская обл',
          postal: '105000',
          country: 'RU',
          type: 'work',
        },
      ],
      events: [{ date: '1977-03-11', type: 'birthday' }],
      groups: [{ id: 'g_doctors', name: 'Врачи' }],
      tags: ['врач', 'здоровье'],
      relationsInternal: [{ contactId: id(10, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-30) + 'T09:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Участковый терапевт. Ежегодный осмотр в мае.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(45) + 'T09:00:00.000Z',
          text: 'Плановый осмотр',
          done: false,
        },
      ],
    }),
    c(10, 10, {
      givenName: 'Ольга',
      familyName: 'Морозова',
      displayName: 'Ольга Морозова',
      phones: [{ value: '+7 916 001 0010', type: 'mobile', primary: true }],
      emails: [{ value: 'omorozov@medcenter.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Медцентр «Здоровье»', title: 'Медсестра', current: true, startDate: '2019-03-01' },
      ],
      events: [{ date: '1991-01-14', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Спорт' }],
      tags: ['медицина', 'здоровье'],
      relationsInternal: [{ contactId: id(9, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-25) + 'T10:00:00.000Z',
      priority: 3,
    }),
    c(11, 11, {
      givenName: 'Максим',
      familyName: 'Волков',
      displayName: 'Максим Волков',
      phones: [{ value: '+7 916 001 0011', type: 'mobile', primary: true }],
      emails: [{ value: 'mvolkov@volkov-realty.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Волков Недвижимость', title: 'Риелтор', current: true, startDate: '2017-05-01' },
      ],
      urls: [{ value: 'https://volkov-realty.ru', type: 'work' }],
      events: [{ date: '1988-06-30', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['недвижимость', 'ипотека'],
      lastContactedAt: relIsoDate(-20) + 'T16:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Помог с поиском квартиры. Знает рынок Москвы.',
    }),
    c(12, 12, {
      givenName: 'Ирина',
      familyName: 'Ковалёва',
      displayName: 'Ирина Ковалёва',
      phones: [{ value: '+7 916 001 0012', type: 'mobile', primary: true }],
      emails: [{ value: 'ikovalev@university.ru', type: 'work', primary: true }],
      organizations: [{ name: 'МГУ', title: 'Профессор', current: true, startDate: '2014-09-01' }],
      events: [{ date: '1979-09-05', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'Учёба' }],
      tags: ['наука', 'ментор'],
      lastContactedAt: relIsoDate(-45) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      imClients: [{ protocol: 'skype', handle: 'irina.kovaleva.mgu' }],
    }),
    c(13, 13, {
      givenName: 'Николай',
      familyName: 'Орлов',
      displayName: 'Николай Орлов',
      phones: [{ value: '+7 916 001 0013', type: 'mobile', primary: true }],
      events: [{ date: '1995-02-22', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'племянник'],
      relationsExternal: [{ person: 'Игорь Орлов', type: 'отец' }],
      priority: 2,
      notesMd: 'Племянник. Учится в политехе.',
    }),
    c(14, 14, {
      givenName: 'Светлана',
      familyName: 'Соловьёва',
      displayName: 'Светлана Соловьёва',
      phones: [{ value: '+7 916 001 0014', type: 'mobile', primary: true }],
      emails: [{ value: 'ssolovev@dsgn.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Дизайн студия DSGN',
          title: 'UX-дизайнер',
          current: true,
          startDate: '2022-02-01',
        },
      ],
      urls: [{ value: 'https://ssoloveva.design', type: 'portfolio' }],
      events: [{ date: '1993-08-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['дизайн', 'ux', 'figma'],
      relationsInternal: [{ contactId: id(15, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-6) + 'T13:00:00.000Z',
      preferredChannel: 'telegram',
      priority: 2,
      socialDetected: [{ platform: 'behance', handle: 'svetlana-soloveva' }],
      customFields: { [coffee]: 'Капучино' },
    }),
    c(15, 15, {
      givenName: 'Алексей',
      familyName: 'Васильев',
      displayName: 'Алексей Васильев',
      phones: [{ value: '+7 916 001 0015', type: 'mobile', primary: true }],
      emails: [{ value: 'avasil@dsgn.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Дизайн студия DSGN',
          title: 'Арт-директор',
          current: true,
          startDate: '2020-09-01',
        },
      ],
      events: [{ date: '1987-06-19', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['дизайн', 'брендинг'],
      relationsInternal: [{ contactId: id(14, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-8) + 'T15:30:00.000Z',
      priority: 3,
    }),
    c(16, 16, {
      givenName: 'Наталья',
      familyName: 'Фёдорова',
      displayName: 'Наталья Фёдорова',
      phones: [{ value: '+7 916 001 0016', type: 'mobile', primary: true }],
      emails: [{ value: 'nfedorov@fitclub.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Фитнес-клуб Energy', title: 'Тренер', current: true, startDate: '2018-01-01' },
      ],
      events: [{ date: '1990-11-03', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Спорт' }],
      tags: ['фитнес', 'тренер', 'здоровье'],
      lastContactedAt: relIsoDate(-7) + 'T07:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Персональный тренер. Тренировки Пн/Ср/Пт в 7 утра.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(1) + 'T06:30:00.000Z',
          text: 'Тренировка утром',
          done: false,
        },
      ],
    }),
    c(17, 17, {
      givenName: 'Михаил',
      familyName: 'Михайлов',
      displayName: 'Михаил Михайлов',
      phones: [{ value: '+7 916 001 0017', type: 'mobile', primary: true }],
      emails: [{ value: 'mmikhail@example.ru', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'ул. Кирова 88',
          city: 'Екатеринбург',
          region: 'Свердловская обл',
          postal: '620000',
          country: 'RU',
          type: 'home',
        },
      ],
      events: [{ date: '1983-04-07', type: 'birthday' }],
      groups: [
        { id: 'g_friends', name: 'Друзья' },
        { id: 'g_school', name: 'Учёба' },
      ],
      tags: ['универ', 'друг', 'хоккей'],
      lastContactedAt: relIsoDate(-21) + 'T19:00:00.000Z',
      priority: 3,
    }),
    c(18, 18, {
      givenName: 'Юлия',
      familyName: 'Беляева',
      displayName: 'Юлия Беляева',
      phones: [{ value: '+7 916 001 0018', type: 'mobile', primary: true }],
      emails: [{ value: 'ybelyaev@sberbank.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Сбербанк',
          title: 'Финансовый консультант',
          current: true,
          startDate: '2016-04-01',
        },
      ],
      events: [{ date: '1984-07-28', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['финансы', 'банк'],
      relationsInternal: [{ contactId: id(19, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-15) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Финансовый консультант. Ведёт инвестиционный портфель.',
      customFields: { [metAt]: '2019-04-22' },
    }),
    c(19, 19, {
      givenName: 'Артём',
      familyName: 'Тарасов',
      displayName: 'Артём Тарасов',
      phones: [{ value: '+7 916 001 0019', type: 'mobile', primary: true }],
      emails: [{ value: 'atarasov@sberbank.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Сбербанк', title: 'Аналитик', current: true, startDate: '2020-07-01' },
      ],
      events: [{ date: '1991-10-16', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['финансы', 'аналитик'],
      relationsInternal: [{ contactId: id(18, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-9) + 'T14:00:00.000Z',
      priority: 3,
    }),
    c(20, 20, {
      givenName: 'Екатерина',
      familyName: 'Белова',
      displayName: 'Екатерина Белова',
      phones: [{ value: '+7 916 001 0020', type: 'mobile', primary: true }],
      emails: [{ value: 'ebelov@example.ru', type: 'personal', primary: true }],
      events: [{ date: '1989-03-01', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'сестра'],
      relationsExternal: [{ person: 'Виктор Белов', type: 'отец' }],
      lastContactedAt: relIsoDate(-3) + 'T20:00:00.000Z',
      preferredChannel: 'phone',
      priority: 1,
      notesMd: 'Сестра. Живёт в Питере. Звонить по воскресеньям.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(6) + 'T19:00:00.000Z',
          text: 'Воскресный звонок',
          done: false,
        },
      ],
    }),
    c(21, 21, {
      givenName: 'Денис',
      familyName: 'Комаров',
      displayName: 'Денис Комаров',
      phones: [{ value: '+7 916 001 0021', type: 'mobile', primary: true }],
      emails: [{ value: 'dkomarov@startuplab.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'StartupLab', title: 'Основатель', current: true, startDate: '2021-01-01' },
      ],
      urls: [
        { value: 'https://startuplab.ru', type: 'work' },
        { value: 'https://linkedin.com/in/dkomarov', type: 'linkedin' },
      ],
      events: [{ date: '1986-01-20', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Работа' },
        { id: 'g_clients', name: 'Клиенты' },
      ],
      tags: ['стартап', 'основатель', 'инвестор'],
      relationsInternal: [{ contactId: id(22, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-11) + 'T16:00:00.000Z',
      preferredChannel: 'telegram',
      priority: 1,
      notesMd: 'Основатель стартапа в SaaS. Хороший нетворкинг.',
      socialDetected: [
        { platform: 'linkedin', handle: 'denis-komarov' },
        { platform: 'twitter', handle: '@dkomarov_builds' },
      ],
    }),
    c(22, 22, {
      givenName: 'Анастасия',
      familyName: 'Орехова',
      displayName: 'Анастасия Орехова',
      phones: [{ value: '+7 916 001 0022', type: 'mobile', primary: true }],
      emails: [{ value: 'aorekhov@startuplab.ru', type: 'work', primary: true }],
      organizations: [{ name: 'StartupLab', title: 'COO', current: true, startDate: '2021-03-01' }],
      events: [{ date: '1988-09-10', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['стартап', 'операции'],
      relationsInternal: [{ contactId: id(21, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-12) + 'T11:00:00.000Z',
      preferredChannel: 'telegram',
      priority: 2,
    }),
    c(23, 23, {
      givenName: 'Илья',
      familyName: 'Семёнов',
      displayName: 'Илья Семёнов',
      phones: [{ value: '+7 916 001 0023', type: 'mobile', primary: true }],
      emails: [{ value: 'ilyaS@example.ru', type: 'personal', primary: true }],
      events: [{ date: '1981-07-04', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['покер', 'футбол'],
      imClients: [{ protocol: 'vk', handle: 'ilya_semenov' }],
      lastContactedAt: relIsoDate(-18) + 'T21:00:00.000Z',
      priority: 3,
    }),
    c(24, 24, {
      givenName: 'Ксения',
      familyName: 'Ильина',
      displayName: 'Ксения Ильина',
      phones: [{ value: '+7 916 001 0024', type: 'mobile', primary: true }],
      emails: [{ value: 'kilyina@school34.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Школа №34', title: 'Учительница', current: true, startDate: '2013-09-01' },
      ],
      events: [{ date: '1980-02-08', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'Учёба' }],
      tags: ['учитель', 'образование'],
      lastContactedAt: relIsoDate(-60) + 'T14:00:00.000Z',
      priority: 3,
      notesMd: 'Классный руководитель ребёнка.',
    }),
    c(25, 25, {
      givenName: 'Григорий',
      familyName: 'Гусев',
      displayName: 'Григорий Гусев',
      phones: [{ value: '+7 916 001 0025', type: 'mobile', primary: true }],
      emails: [{ value: 'grigoriy.g@example.ru', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'пр. Победы 15',
          city: 'Новосибирск',
          region: 'Новосибирская обл',
          postal: '630000',
          country: 'RU',
          type: 'home',
        },
      ],
      events: [{ date: '1986-11-17', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['музыка', 'гитара', 'группа'],
      imClients: [{ protocol: 'telegram', handle: '@grigoriy_gusev' }],
      lastContactedAt: relIsoDate(-28) + 'T22:00:00.000Z',
      priority: 3,
    }),
    c(26, 26, {
      givenName: 'Надежда',
      familyName: 'Зайцева',
      displayName: 'Надежда Зайцева',
      phones: [{ value: '+7 916 001 0026', type: 'mobile', primary: true }],
      emails: [{ value: 'nzaytsev@example.ru', type: 'personal', primary: true }],
      events: [{ date: '1983-08-25', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'кузина'],
      relationsExternal: [{ person: 'Пётр Зайцев', type: 'отец' }],
      lastContactedAt: relIsoDate(-35) + 'T15:00:00.000Z',
      priority: 2,
    }),
    c(27, 27, {
      givenName: 'Виктор',
      familyName: 'Степанов',
      displayName: 'Виктор Степанов',
      phones: [{ value: '+7 916 001 0027', type: 'mobile', primary: true }],
      emails: [{ value: 'vstepanov@editor-ru.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Редакция «Слово»', title: 'Редактор', current: true, startDate: '2019-11-01' },
      ],
      urls: [{ value: 'https://victor-stepanov.ru', type: 'blog' }],
      events: [{ date: '1979-05-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['редактор', 'книги'],
      lastContactedAt: relIsoDate(-22) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 3,
      notesMd: 'Редактор. Хорош для вычитки текстов.',
    }),
    c(28, 28, {
      givenName: 'Полина',
      familyName: 'Богданова',
      displayName: 'Полина Богданова',
      phones: [{ value: '+7 916 001 0028', type: 'mobile', primary: true }],
      events: [{ date: '1994-01-28', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Спорт' }],
      tags: ['йога', 'медитация', 'велнес'],
      imClients: [{ protocol: 'whatsapp', handle: '+7 916 001 0028' }],
      lastContactedAt: relIsoDate(-13) + 'T08:00:00.000Z',
      priority: 3,
    }),
    c(29, 29, {
      givenName: 'Роман',
      familyName: 'Никитин',
      displayName: 'Роман Никитин',
      phones: [{ value: '+7 916 001 0029', type: 'mobile', primary: true }],
      emails: [{ value: 'rnikitin@cybersec.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'КиберЗащита ООО',
          title: 'Руководитель ИБ',
          current: true,
          startDate: '2021-06-01',
        },
      ],
      urls: [{ value: 'https://github.com/roman-nikitin', type: 'github' }],
      events: [{ date: '1990-03-22', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['безопасность', 'dev', 'ctf'],
      relationsInternal: [{ contactId: id(30, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-16) + 'T17:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      socialDetected: [{ platform: 'github', handle: 'roman-nikitin' }],
    }),
    c(30, 30, {
      givenName: 'Алина',
      familyName: 'Сорокина',
      displayName: 'Алина Сорокина',
      phones: [{ value: '+7 916 001 0030', type: 'mobile', primary: true }],
      emails: [{ value: 'asorokin@cybersec.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'КиберЗащита ООО',
          title: 'DevOps-инженер',
          current: true,
          startDate: '2022-01-15',
        },
      ],
      events: [{ date: '1993-07-11', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['devops', 'облако'],
      relationsInternal: [{ contactId: id(29, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-19) + 'T11:00:00.000Z',
      priority: 3,
    }),
    c(31, 31, {
      givenName: 'Павел',
      familyName: 'Фомин',
      displayName: 'Павел Фомин',
      phones: [{ value: '+7 916 001 0031', type: 'mobile', primary: true }],
      addresses: [{ city: 'Краснодар', country: 'RU', type: 'home' }],
      events: [{ date: '1976-01-31', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'дядя'],
      priority: 2,
      notesMd: 'Дядя Паша. На пенсии, живёт в Краснодаре.',
    }),
    c(32, 32, {
      givenName: 'Дарья',
      familyName: 'Андреева',
      displayName: 'Дарья Андреева',
      phones: [{ value: '+7 916 001 0032', type: 'mobile', primary: true }],
      emails: [{ value: 'dandreyev@prbridge.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'PR Мост', title: 'Менеджер по PR', current: true, startDate: '2018-08-01' },
      ],
      events: [{ date: '1988-10-20', type: 'birthday' }],
      groups: [
        { id: 'g_work', name: 'Работа' },
        { id: 'g_clients', name: 'Клиенты' },
      ],
      tags: ['pr', 'медиа', 'нетворкинг'],
      lastContactedAt: relIsoDate(-8) + 'T12:00:00.000Z',
      preferredChannel: 'telegram',
      priority: 2,
      notesMd: 'Ключевой контакт по пресс-релизам.',
      socialDetected: [{ platform: 'vk', handle: 'dasha_andreeva_pr' }],
    }),
    c(33, 33, {
      givenName: 'Антон',
      familyName: 'Александров',
      displayName: 'Антон Александров',
      phones: [{ value: '+7 916 001 0033', type: 'mobile', primary: true }],
      emails: [{ value: 'anton@santehnik.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Сантехник-Москва', title: 'Владелец', current: true, startDate: '2010-01-01' },
      ],
      events: [{ date: '1972-06-15', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['сантехник', 'ремонт'],
      lastContactedAt: relIsoDate(-90) + 'T10:00:00.000Z',
      priority: 3,
    }),
    c(34, 34, {
      givenName: 'Виктория',
      familyName: 'Громова',
      displayName: 'Виктория Громова',
      phones: [{ value: '+7 916 001 0034', type: 'mobile', primary: true }],
      emails: [{ value: 'vgromov@audit-firm.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Аудит-Профи', title: 'Бухгалтер', current: true, startDate: '2020-04-01' },
      ],
      addresses: [{ city: 'Москва', country: 'RU', type: 'work' }],
      events: [{ date: '1990-02-27', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['бухгалтерия', 'налоги'],
      lastContactedAt: relIsoDate(-40) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Бухгалтер. Готовит годовую отчётность.',
      customFields: { [metAt]: '2020-01-20' },
    }),
    c(35, 35, {
      givenName: 'Олег',
      familyName: 'Краснов',
      displayName: 'Олег Краснов',
      phones: [{ value: '+7 916 001 0035', type: 'mobile', primary: true }],
      emails: [{ value: 'oleg.krasnov@example.ru', type: 'personal', primary: true }],
      events: [{ date: '1996-04-01', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'Учёба' }],
      tags: ['одногруппник', 'учёба'],
      imClients: [{ protocol: 'vk', handle: 'oleg_krasnov_96' }],
      lastContactedAt: relIsoDate(-50) + 'T20:00:00.000Z',
      priority: 3,
    }),
    c(36, 36, {
      givenName: 'Валерия',
      familyName: 'Маслова',
      displayName: 'Валерия Маслова',
      phones: [{ value: '+7 916 001 0036', type: 'mobile', primary: true }],
      emails: [{ value: 'vmaslova@nutri.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'NutriПлан', title: 'Диетолог', current: true, startDate: '2019-01-01' },
      ],
      events: [{ date: '1987-07-17', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Спорт' }],
      tags: ['питание', 'здоровье', 'велнес'],
      lastContactedAt: relIsoDate(-25) + 'T12:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Диетолог. Консультация раз в квартал.',
      customFields: { [coffee]: 'Чёрный кофе' },
    }),
    c(37, 37, {
      givenName: 'Игорь',
      familyName: 'Зимин',
      displayName: 'Игорь Зимин',
      phones: [{ value: '+7 916 001 0037', type: 'mobile', primary: true }],
      emails: [{ value: 'izimin@support.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'ТехПоддержка', title: 'Руководитель', current: true, startDate: '2021-07-01' },
      ],
      events: [{ date: '1989-01-10', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['поддержка', 'it'],
      lastContactedAt: relIsoDate(-5) + 'T09:00:00.000Z',
      priority: 3,
    }),
    c(38, 38, {
      givenName: 'Кристина',
      familyName: 'Мельникова',
      displayName: 'Кристина Мельникова',
      phones: [{ value: '+7 916 001 0038', type: 'mobile', primary: true }],
      emails: [{ value: 'kristina.mel@example.ru', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'ул. Садовая 200',
          city: 'Краснодар',
          region: 'Краснодарский край',
          postal: '350000',
          country: 'RU',
          type: 'home',
        },
      ],
      events: [{ date: '1992-05-06', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['путешествия', 'фотография'],
      imClients: [{ protocol: 'instagram', handle: '@kristina.travel' }],
      lastContactedAt: relIsoDate(-17) + 'T18:00:00.000Z',
      preferredChannel: 'instagram',
      priority: 3,
      socialDetected: [{ platform: 'instagram', handle: 'kristina.travel' }],
    }),
    c(39, 39, {
      givenName: 'Кирилл',
      familyName: 'Богданов',
      displayName: 'Кирилл Богданов',
      phones: [{ value: '+7 916 001 0039', type: 'mobile', primary: true }],
      emails: [{ value: 'kbogdanov@growth-ru.com', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Growth Agency',
          title: 'Директор по маркетингу',
          current: true,
          startDate: '2019-05-01',
        },
      ],
      urls: [{ value: 'https://growth-ru.com', type: 'work' }],
      events: [{ date: '1985-09-13', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['маркетинг', 'рост', 'seo'],
      relationsInternal: [{ contactId: id(40, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-6) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Маркетинговый партнёр. Совместные кампании.',
      socialDetected: [{ platform: 'linkedin', handle: 'kirill-bogdanov' }],
    }),
    c(40, 40, {
      givenName: 'Елизавета',
      familyName: 'Быкова',
      displayName: 'Елизавета Быкова',
      phones: [{ value: '+7 916 001 0040', type: 'mobile', primary: true }],
      emails: [{ value: 'ebykova@growth-ru.com', type: 'work', primary: true }],
      organizations: [
        { name: 'Growth Agency', title: 'Контент-стратег', current: true, startDate: '2020-09-01' },
      ],
      events: [{ date: '1994-02-08', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['контент', 'копирайтинг'],
      relationsInternal: [{ contactId: id(39, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-13) + 'T16:00:00.000Z',
      priority: 3,
    }),
    c(41, 41, {
      givenName: 'Глеб',
      familyName: 'Романов',
      displayName: 'Глеб Романов',
      phones: [{ value: '+7 916 001 0041', type: 'mobile', primary: true }],
      emails: [{ value: 'gleb.romanov@example.ru', type: 'personal', primary: true }],
      events: [{ date: '1980-06-28', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'шурин'],
      relationsExternal: [{ person: 'Анна Кузнецова', type: 'сестра' }],
      lastContactedAt: relIsoDate(-30) + 'T11:00:00.000Z',
      priority: 2,
    }),
    c(42, 42, {
      givenName: 'Маргарита',
      familyName: 'Фокина',
      displayName: 'Маргарита Фокина',
      phones: [{ value: '+7 916 001 0042', type: 'mobile', primary: true }],
      emails: [{ value: 'mfokina@archstudio.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'АрхСтудия', title: 'Архитектор', current: true, startDate: '2017-03-01' },
      ],
      urls: [{ value: 'https://archstudio.ru/margrita', type: 'portfolio' }],
      events: [{ date: '1986-03-04', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['архитектура', 'дизайн'],
      lastContactedAt: relIsoDate(-22) + 'T14:00:00.000Z',
      preferredChannel: 'email',
      priority: 3,
      notesMd: 'Архитектор. Консультировала по ремонту.',
    }),
    c(43, 43, {
      givenName: 'Тимофей',
      familyName: 'Дёмин',
      displayName: 'Тимофей Дёмин',
      phones: [{ value: '+7 916 001 0043', type: 'mobile', primary: true }],
      addresses: [{ city: 'Волгоград', country: 'RU', type: 'home' }],
      events: [{ date: '1970-08-19', type: 'birthday' }],
      groups: [{ id: 'g_family', name: 'Семья' }],
      tags: ['семья', 'дедушка'],
      priority: 1,
      notesMd: 'Дедушка. Звонить по воскресеньям.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(0) + 'T18:00:00.000Z',
          text: 'Воскресный звонок дедушке',
          done: false,
        },
      ],
    }),
    c(44, 44, {
      givenName: 'Алиса',
      familyName: 'Ермакова',
      displayName: 'Алиса Ермакова',
      phones: [{ value: '+7 916 001 0044', type: 'mobile', primary: true }],
      emails: [{ value: 'aermakov@wellness.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Велнес Центр',
          title: 'Инструктор по йоге',
          current: true,
          startDate: '2020-06-01',
        },
      ],
      events: [{ date: '1991-02-21', type: 'birthday' }],
      groups: [{ id: 'g_health', name: 'Спорт' }],
      tags: ['йога', 'осознанность', 'велнес'],
      imClients: [{ protocol: 'telegram', handle: '@alisa_yoga' }],
      lastContactedAt: relIsoDate(-7) + 'T08:30:00.000Z',
      preferredChannel: 'telegram',
      priority: 3,
    }),
    c(45, 45, {
      givenName: 'Вадим',
      familyName: 'Голубев',
      displayName: 'Вадим Голубев',
      phones: [{ value: '+7 916 001 0045', type: 'mobile', primary: true }],
      emails: [{ value: 'vgolubev@cloud-spb.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Cloud SPB', title: 'Архитектор решений', current: true, startDate: '2018-11-01' },
      ],
      addresses: [{ city: 'Санкт-Петербург', country: 'RU', type: 'home' }],
      events: [{ date: '1987-10-14', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['облако', 'aws', 'архитектура'],
      relationsInternal: [{ contactId: id(46, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-4) + 'T13:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
      notesMd: 'Специалист по облачным решениям. AWS сертификат.',
      socialDetected: [{ platform: 'linkedin', handle: 'vadim-golubev-cloud' }],
      customFields: { [coffee]: 'Американо', [metAt]: '2022-06-12' },
    }),
    c(46, 46, {
      givenName: 'Ангелина',
      familyName: 'Тимофеева',
      displayName: 'Ангелина Тимофеева',
      phones: [{ value: '+7 916 001 0046', type: 'mobile', primary: true }],
      emails: [{ value: 'atimofeyev@cloud-spb.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Cloud SPB',
          title: 'Руководитель проектов',
          current: true,
          startDate: '2019-02-01',
        },
      ],
      events: [{ date: '1990-05-23', type: 'birthday' }],
      groups: [{ id: 'g_work', name: 'Работа' }],
      tags: ['pm', 'agile', 'облако'],
      relationsInternal: [{ contactId: id(45, ctx), type: 'colleague' }],
      lastContactedAt: relIsoDate(-9) + 'T15:00:00.000Z',
      priority: 3,
    }),
    c(47, 47, {
      givenName: 'Эльдар',
      familyName: 'Самойлов',
      displayName: 'Эльдар Самойлов',
      phones: [{ value: '+7 916 001 0047', type: 'mobile', primary: true }],
      emails: [{ value: 'esamoylov@legal-m.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Юридическая фирма «Самойлов»',
          title: 'Адвокат',
          current: true,
          startDate: '2016-01-01',
        },
      ],
      events: [{ date: '1980-11-30', type: 'birthday' }],
      groups: [{ id: 'g_clients', name: 'Клиенты' }],
      tags: ['юрист', 'адвокат'],
      lastContactedAt: relIsoDate(-55) + 'T10:00:00.000Z',
      preferredChannel: 'email',
      priority: 2,
    }),
    c(48, 48, {
      givenName: 'Софья',
      familyName: 'Логинова',
      displayName: 'Софья Логинова',
      phones: [{ value: '+7 916 001 0048', type: 'mobile', primary: true }],
      emails: [{ value: 'sloginov@school34.ru', type: 'work', primary: true }],
      organizations: [
        { name: 'Школа №34', title: 'Директор', current: true, startDate: '2010-08-01' },
      ],
      events: [{ date: '1968-01-19', type: 'birthday' }],
      groups: [{ id: 'g_school', name: 'Учёба' }],
      tags: ['образование', 'директор'],
      lastContactedAt: relIsoDate(-120) + 'T09:00:00.000Z',
      priority: 3,
      notesMd: 'Директор школы.',
    }),
    c(49, 49, {
      givenName: 'Артур',
      familyName: 'Чернов',
      displayName: 'Артур Чернов',
      phones: [{ value: '+7 916 001 0049', type: 'mobile', primary: true }],
      emails: [{ value: 'achernov@dentclinic.ru', type: 'work', primary: true }],
      organizations: [
        {
          name: 'Стоматология «Улыбка»',
          title: 'Стоматолог',
          current: true,
          startDate: '2014-05-01',
        },
      ],
      addresses: [
        {
          street: 'ул. Медицинская 500',
          city: 'Москва',
          region: 'Московская обл',
          postal: '115000',
          country: 'RU',
          type: 'work',
        },
      ],
      events: [{ date: '1978-07-22', type: 'birthday' }],
      groups: [{ id: 'g_doctors', name: 'Врачи' }],
      tags: ['стоматолог', 'здоровье'],
      lastContactedAt: relIsoDate(-180) + 'T11:00:00.000Z',
      preferredChannel: 'phone',
      priority: 2,
      notesMd: 'Стоматолог. Плановый осмотр раз в полгода.',
      reminders: [
        {
          id: rndCrockford(),
          date: relIsoDate(30) + 'T10:00:00.000Z',
          text: 'Записаться к стоматологу',
          done: false,
        },
      ],
      userDefined: { appointmentFrequency: 'biannual' },
    }),
    c(50, 50, {
      givenName: 'Милана',
      familyName: 'Юдина',
      displayName: 'Милана Юдина',
      phones: [{ value: '+7 916 001 0050', type: 'mobile', primary: true }],
      emails: [{ value: 'milana.yudina@example.ru', type: 'personal', primary: true }],
      addresses: [
        {
          street: 'Набережная 3',
          city: 'Сочи',
          region: 'Краснодарский край',
          postal: '354000',
          country: 'RU',
          type: 'home',
        },
      ],
      events: [{ date: '1995-03-10', type: 'birthday' }],
      groups: [{ id: 'g_friends', name: 'Друзья' }],
      tags: ['путешествия', 'море', 'яхтинг'],
      imClients: [{ protocol: 'whatsapp', handle: '+7 916 001 0050' }],
      lastContactedAt: relIsoDate(-24) + 'T19:00:00.000Z',
      preferredChannel: 'whatsapp',
      priority: 3,
      notesMd: 'Подруга из универа. Живёт в Сочи.',
      socialDetected: [{ platform: 'instagram', handle: 'milana.yudina.sochi' }],
      customFields: { [bonus]: 'МЮ-5521987' },
      userDefined: { vacationCity: 'Sochi' },
    }),
  ]
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Build a curated 50-contact bundle for the chosen locale. Stable IDs within one call. */
export function buildDemoContacts(locale: 'en' | 'ru', deviceId: string): DemoBundle {
  const idMap: Record<number, Ulid> = {}
  const now = new Date().toISOString()
  const defs: CustomFieldDef[] = [
    {
      id: rndCrockford(),
      name: 'preferredCoffee',
      type: 'text',
      createdAt: now,
      updatedAt: now,
      lamportTs: 1,
      deviceId,
    } as CustomFieldDef,
    {
      id: rndCrockford(),
      name: 'bonusCardNumber',
      type: 'text',
      createdAt: now,
      updatedAt: now,
      lamportTs: 2,
      deviceId,
    } as CustomFieldDef,
    {
      id: rndCrockford(),
      name: 'metAt',
      type: 'date',
      createdAt: now,
      updatedAt: now,
      lamportTs: 3,
      deviceId,
    } as CustomFieldDef,
  ]
  const ctx: BuildCtx = {
    locale,
    deviceId,
    now,
    idMap,
    defs,
    defIds: { coffee: defs[0]!.id, bonus: defs[1]!.id, metAt: defs[2]!.id },
  }
  const contacts = locale === 'en' ? buildEn(ctx) : buildRu(ctx)
  // Collect distinct groups referenced in contact array
  const seenGroups = new Map<string, GroupMembership>()
  for (const c of contacts) {
    for (const g of c.groups ?? []) {
      if (!seenGroups.has(g.id)) seenGroups.set(g.id, g)
    }
  }
  return { contacts, groups: [...seenGroups.values()], customFieldDefs: defs }
}

/** Insert the demo bundle into the DB and set meta.demo_seeded = locale. Idempotent: throws if already seeded. */
export async function loadDemo(
  db: DbAdapter,
  deviceId: string,
  locale: 'en' | 'ru',
): Promise<void> {
  const seeded = await getDemoSeed(db)
  if (seeded) throw new Error(`demo data already loaded (${seeded})`)
  const bundle = buildDemoContacts(locale, deviceId)
  const repo = makeContactsRepo(db, deviceId)
  const defsRepo = makeCustomFieldDefsRepo(db, deviceId)
  // Bulk-load custom field definitions
  for (const def of bundle.customFieldDefs) await defsRepo.upsert(def)
  // Bulk-load contacts in a single transaction
  await repo.bulkLoad(bundle.contacts)
  // Mark as seeded
  await db.execute(
    `INSERT INTO meta (key, value) VALUES ('demo_seeded', ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
    [locale],
  )
}

/** Returns the seeded locale, or null if no demo data has been loaded. */
export async function getDemoSeed(db: DbAdapter): Promise<string | null> {
  const rows = await db.select<{ value: string }>("SELECT value FROM meta WHERE key='demo_seeded'")
  return rows[0]?.value ?? null
}
